databaseName: modular_api

service:
  type: NodePort
  port: 8085
  nodePort: 32105

image:
  repository: public.ecr.aws/x4s4z8e1/syndicate/modular-api
  tag: 5.4.0-rule-engine
  pullPolicy: IfNotPresent

replicas: 1

mongoService: mongo
mongoPort: 27017
vaultService: vault
vaultPort: 8200