apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}-console
  labels:
    app.kubernetes.io/name: {{ include "minio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "minio.chart" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "minio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.consoleService.type }}
  ports:
    - protocol: TCP
      name: console
      targetPort: 9001
      port: {{ .Values.consoleService.port }}
      {{- if (and (eq .Values.consoleService.type "NodePort") ( .Values.consoleService.nodePort)) }}
      nodePort: {{ .Values.consoleService.nodePort }}
      {{- end }}
